# App
spring.application.name=IGugulam-Community-Program-Backend
server.port=8080

# In-memory H2 database (dev only)
spring.datasource.url=jdbc:h2:mem:igugulam
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 web console at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true